
CREATE TABLE IF NOT EXISTS peaks (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  usgsid INTEGER NOT NULL,
  state CHARACTER(2) NOT NULL,
  county VARCHAR NOT NULL,
  map VARCHAR NOT NULL,
  elevation SMALLINT NOT NULL,
  location GEOMETRY(POINT, 4326) NOT NULL
);

COMMIT;