addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.22")
addSbtPlugin("org.portable-scala" % "sbt-crossproject" % "0.3.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.3.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.3")
//addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.6.0")
//addSbtPlugin("com.lihaoyi" % "workbench" % "0.2.3")
