addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.16")
addSbtPlugin("org.scala-native" % "sbt-crossproject" % "0.2.0")
addSbtPlugin("org.scala-native" % "sbt-scalajs-crossproject" % "0.2.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.2.0")
//addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.6.0")
//addSbtPlugin("com.lihaoyi" % "workbench" % "0.2.3")
